### ISSUE TITLE
Emails are Case Sensitive

### ISSUE THREAD

**Issue by MarwaKhalid** [SamanthaGuillemette/SOEN390#285]
Emails are case sensitive, this means if we are trying to find the user's document based on their email, we MUST take into account the cases otherwise our application won't find the document in firebase.

auth.currentUser?.email; DOES NOT WORK! it stores the email as lowercase!

**Comment by smarkandu** [comment]
Assigned to @tusharraval102 since he deals with credentials/authentication.

**Comment by smarkandu** [comment]
I looks like when we login, whatever we enter needs to match exactly whats stored in the DB for the email (since we use it as "key" for both the Admin and Client table):

![image](https://user-images.githubusercontent.com/48603412/160172611-8212879d-35da-4b47-aac0-3357ae21d63f.png)

I'd recommend setting the key/email to either all lowercase or all uppercase when we first create the key in the DB, then whenever we try to access it, we do the same for the requested key when we try to query for it.

**Comment by smarkandu** [comment]
Example of a bad entry in the DB:

![image](https://user-images.githubusercontent.com/48603412/160175510-4842d6aa-f203-436c-952e-d1c832327ca8.png)
